version: "3.9"
services:
  postgres:
    image: postgres:14.6-alpine
    environment:
      POSTGRES_DB: "greenlight"
      POSTGRES_USER: "postgresql"
      POSTGRES_PASSWORD: "password"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "1234:5432"
